version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
    ports:
      - "8848:8848"