version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=3000
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-name-resolve=true
      --transaction_isolation=REPEATABLE-READ
    environment:
      MYSQL_USER: chen
      MYSQL_ROOT_PASSWORD: chen
      MYSQL_PASSWORD: chen
    ports:
      - "3306:3306"
    volumes:
      #mysql数据库挂载到host物理机目录
      - "/data/docker/mysql5.7/data/db:/var/lib/mysql"
      #容器的配置目录挂载到host物理机目录
      - "/data/docker/mysql5.7/data/conf:/etc/mysql/conf.d"
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server /etc/redis.conf # 启动redis命令
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - /data/redis/data:/data
      - /data/redis/redis.conf:/etc/redis.conf
    ports:
      - "6379:6379"
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    restart: always
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=ip
      #      - BASE_DIR=/home/nacos
      #      - CLASSPATH=.:/home/nacos/conf:$CLASSPATH
      #      - CLUSTER_CONF=/home/nacos/conf/cluster.conf
      - FUNCTION_MODE=all
      - NACOS_USER="nacos
      #      - JAVA=/usr/lib/jvm/java-8-oracle/bin/java
      - NACOS_SERVER_PORT=8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_develop
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=chen
    depends_on:
      - mysql
    ports:
      - '8848:8848'