server:
  port: 10002
spring:
  application:
    name: auth-server
  profiles:
    active: dev #def
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.200:3306/ag_auth_v1?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: chen
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: AuthServerDataSourceHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.0.200
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  boot:
    admin:
      client:
        enabled: true
        username: admin
        password: admin

#开启端点
management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#  开启熔断降级
feign:
  sentinel:
    enabled: true
# hystrix 熔断配置
log:
  base: "E:\\"
  level: warn


