server:
  port: 10002
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.200:3306/ag_auth_v1?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: chen
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: AuthServerDataSourceHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.0.200
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1

#  开启熔断降级
feign:
  sentinel:
    enabled: true
log:
  base: "E:\\"
  level: debug

swagger2:
  enable: true
  info:
    title: "鉴权中心"
    desc: "鉴权中心"
    url: http://localhost:${server.port}
    version: 1
    basePackage: com.github.canglan.cm



