server:
  port: 10005
  max-http-header-size: 20480
spring:
#  messages:
#    basename: i18n/messages
  redis:
    host: localhost
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1

logging:
  level:
    com.github.canglan.cm: debug
    com.alibaba.nacos.client.naming: error
    com.baomidou.mybatisplus.spring: debug

#  开启熔断降级
feign:
  sentinel:
    enabled: true

# 设置 负载均衡 ribbon 的重试次数以及读取超时时间
ribbon:
  MaxAutoRetries: 3
  ReadTimeout: 3000
# 认证服务ID
security:
  auth-service-id: auth-server

log:
  base: "E:\\"
#  level: warn
  level: debug

swagger2:
  enable: true
  info:
    title: "测试2"
    desc: "测试2"
    url: http://localhost:${server.port}
    version: 1
    basePackage: com.github.canglan.cm
