server:
  port: 10002
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/ag_admin_v1?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: chen
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: AuthServerDataSourceHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
logging:
  level:
    com.github.canglan.cm: debug
    com.alibaba.nacos.client.naming: error
    com.baomidou.mybatisplus.spring: debug

auth:
  client:
    token-header: x-client-token
  user:
    token-header: Authorization
    ## 服务名称
    service-name: admin

#  开启熔断降级
feign:
  hystrix:
    enabled: true
# hystrix 熔断配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
log:
  base: "E:\\"

