spring:
  application:
    name: client
server:
  port: 10003

#security:
#  oauth2:
#    client:
#      client-id: myapp
#      client-secret: lxapp
#      user-authorization-uri: http://localhost:8081/oauth/authorize
#      access-token-uri: http://localhost:8081/oauth/token
#      refresh-token-validity-seconds: 60
auth:
  resource:
    token-header: x-client-token
  serviceId: auth-server

#  开启熔断降级
feign:
  hystrix:
    enabled: true
# hystrix 熔断配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000