server:
  port: 10004
  max-http-header-size: 20480
spring:
  redis:
    host: localhost
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    com.github.canglan.cm: debug
    com.alibaba.nacos.client.naming: error
    com.baomidou.mybatisplus.spring: debug

#  开启熔断降级
feign:
  hystrix:
    enabled: true
# hystrix 熔断配置
hystrix:
  #  shareSecurityContext: true
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# 设置 负载均衡 ribbon 的重试次数以及读取超时时间
ribbon:
  MaxAutoRetries: 3
  ReadTimeout: 3000


log:
  base: "E:\\"
  level: warn

swagger2:
  enable: true
  info:
    title: "测试1"
    desc: "测试1"
    url: http://localhost:${server.port}
    version: 1
    basePackage: com.github.canglan.cm

security:
  auth-service-id: auth-server