server:
  port: 10001
  #   设置请求头大小
  max-http-header-size: 20480
spring:
  redis:
    host: 192.168.0.200
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务注册与发现
          lower-case-service-id: true # 将服务名大写转小写
      routes:
        - id: auth-server
          uri: lb://auth-server
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
        - id: auth-server
          uri: lb://cm-test-1
          order: 8000
          predicates:
            - Path=/test1/**
          filters:
            - StripPrefix=1   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
        - id: auth-server
          uri: lb://cm-test-2
          order: 8000
          predicates:
            - Path=/test2/**
          filters:
            - StripPrefix=1   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
project:
  name: ${spring.application.name}
logging:
  level:
    com.github.canglan.cm: debug
    com.alibaba.nacos.client.naming: error
    com.baomidou.mybatisplus.spring: debug

#  开启熔断降级
feign:
  client:
    config:
      defualt:           #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 12000
  sentinel:
    enabled: true
  httpclient:
    enabled: false
    connection-timeout: 5000
# 设置 负载均衡 ribbon 的重试次数以及读取超时时间
ribbon:
  MaxAutoRetries: 3
  ReadTimeout: 5000 # 连接所需时间，默认3秒，一般不够
  ConnectTimeout: 5000 # 读取到可用资源的时间，默认一秒，不够，需要改为 5 秒

# 日志存储路径
log:
  base: "E:\\"
  #日志等级，并且控制 logback
  level: debug

# 网关放开连接
gate:
  authentication:
    ignore-urls: /oauth,/v2

# 客户端认证属性配置
security:
  auth-service-id: "auth-server"
  oauth2:
    grant-type: password
    scope: all
    client-id: test
    client-secret: admin

swagger2:
  enable: false

