server:
  port: 10001
  max-http-header-size: 20480
spring:
  #  datasource:
  #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #    url: jdbc:p6spy:mysql://localhost:3306/ag_auth_v1?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  #    username: root
  #    password: chen
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      minimum-idle: 5
  #      maximum-pool-size: 15
  #      auto-commit: true
  #      idle-timeout: 30000
  #      pool-name: AuthServerDataSourceHikariCP
  #      max-lifetime: 1800000
  #      connection-timeout: 30000
  #      connection-test-query: SELECT 1
  redis:
    host: localhost
    password: null
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务注册与发现
          lower-case-service-id: true # 将服务名大写转小写
      routes:
        - id: auth-server
          uri: lb://auth-server
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
        - id: auth-server
          uri: lb://cm-test-1
          order: 8000
          predicates:
            - Path=/test1/**
          filters:
            - StripPrefix=1   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
        - id: auth-server
          uri: lb://cm-test-2
          order: 8000
          predicates:
            - Path=/test2/**
          filters:
            - StripPrefix=1   #StripPrefix 表明 忽略前缀路径  /api/auth/xxx ==> /xxx
logging:
  level:
    com.github.canglan.cm: debug
    com.alibaba.nacos.client.naming: error
    com.baomidou.mybatisplus.spring: debug

#  开启熔断降级
feign:
  hystrix:
    enabled: true
# hystrix 熔断配置
hystrix:
#  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  propagate:
    request-attribute:
      enabled: false
ribbon:
  MaxAutoRetries: 3
  ReadTimeout: 3000

log:
  base: "E:\\"

# 网关放开连接
gate:
  authentication:
    ignore-urls: /oauth

# 认证配置
security:
  auth-service-id: "auth-server"
  oauth2:
    grant-type: password
    scope: all
    client-id: test
    client-secret: admin